### ISSUE TITLE
Support various methods for groups

### ISSUE THREAD

**Issue by miladh** [CINPLA/exdir#13]
- [x] `keys()`
- [x] `values()`
- [x] `items()`
- [x] `iter()`
- [x] `get()`
- [ ]  Intermediate groups can be created automatically  "grp = f.create_group('foo/bar/baz')"
- [ ] `__del__()`
- [ ] `__str__()`
- [ ] `__repr__()`
- [x] `__len__()`
- [ ] `copy()`

**Comment by lepmik** [comment]
I do not think we should implement `__del__`; see #83 

Also, this issue seems redundant when compared with #36, thus I copy this list to that issue and close this one.
