### ISSUE TITLE
get all attrs from object

### ISSUE THREAD

**Issue by lepmik** [CINPLA/exdir#18]
as it is now if you want all attributes to a dictionary you must use
```python
attributes = group.attrs._open_or_create()
```
we should have a method that wraps this, e.g.
```python
attributes = group.attrs[()]
```
Another option is
```python
attributes = dict(group.attrs)
```
but here nested dictionaries in `attrs` will give a `dict` with `Attribute` object inside.

**Comment by miladh** [comment]
This can be done by:

```python
attributes = group.attrs.to_dict()
```
