### ISSUE TITLE
Smart checking of valid filenames

### ISSUE THREAD

**Issue by simetenn** [CINPLA/exdir#23]
We need a smart checking of valid file names, that checks if a file name is allowed on both Linux, Windows and Mac.

It must be able to handle case insensitive file names on Windows but checking all existing files in an exdir file and return false if the false exists in another case version.

**Comment by simetenn** [comment]
Invalid Windows [file names](https://msdn.microsoft.com/en-us/library/aa365247)

**Comment by dragly** [comment]
We discussed three levels of checking:

- strict: only allow numbers, lowercase, underscore (_) and dash (-), fast
- simple: allow numbers, lowercase, uppercase, underscore (_) and dash (-), check if any file exists with same name in any case, a bit slow, enabled by default for now
- thorough: verify if name is safe on all platforms, also check if existing files may conflict with a create file. Slow, maybe enabled by default in the future if we can make it fast
- none: allows any filename, issues handled by user, simple to implement

**Comment by simetenn** [comment]
We need to decide what should be the intended behaviour when opening an exdir file with regards to a previously set naming rule. There are cases where "strict" naming is less strict than "simple". 

This works, but can potentially create problems when on windows. Should we take this into account at all?

    f = File("testfile.exdir", "w", naming_rule='none')
    f.create_group("AAA")
    f.close()

    f = File("testfile.exdir", "a", naming_rule='strict')
    f.create_group("aaa")
    f.close()

    
This gives us an error message, and "strict" is here less strict than "simple"

    f = File("testfile.exdir", "w", naming_rule='none')
    f.create_group("AAA")
    f.close()

    # This works, but can potentially create problems when on windows
    f = File("testfile.exdir", "a", naming_rule='simple')
    f.create_group("aaa")
    f.close()

**Comment by dragly** [comment]
Oh, my naming of the levels is apparently really bad. What about this instead?

- unchecked: only allow numbers, lowercase, underscore (_) and dash (-), fast
- checked: allow numbers, lowercase, uppercase, underscore (_) and dash (-), check if any file exists with same name in any case, a bit slow, enabled by default for now
- thorough: verify if name is safe on all platforms, also check if existing files may conflict with a create file. Slow, maybe enabled by default in the future if we can make it fast
- none: allows any filename, issues handled by user, simple to implement

**Comment by lepmik** [comment]
As far as I understand this is solved, closing it, please reopen if something is still unresolved.
