### ISSUE TITLE
Make use of quantities in exdir into a plugin

### ISSUE THREAD

**Issue by dragly** [CINPLA/exdir#26]
We still want to enforce quantities by default, but it might be beneficial to provide an option to disable it for users without quantities installed or who wish not to use the automatic conversion.

**Comment by dragly** [comment]
We should push this forward to 1.0 and make the current implementation of quantities in exdir into a plugin.

**Comment by simetenn** [comment]
This is solved in pull request #38, by quantities becoming a plugin.
