### ISSUE TITLE
reading from server is slow

### ISSUE THREAD

**Issue by lepmik** [CINPLA/exdir#28]
After testing a bit I find that reading a dataset from a server is slow compared to reading the same dataset with only binary files (compared neo.exdirio and neo.axonaio with the same dataset). It thus seems that the attributes files are consuming a lot of reading time since for each time an attribute is retrieved a file is opened.

**Comment by dragly** [comment]
@lepmik was the fix you mentioned (archiving and transferring the data into a cache) in expipe or exdir? We should write some performance tests that compares HDF5, exdir and other binary formats over different types of network and local drives.

I expect binary formats to be faster, but if there is an order of magnitude difference, I am starting to think that the network filesystems are to blame or the way we are using them. It might be an idea to include the archive+transfer cache as part of exdir, although I would really prefer to avoid it.

**Comment by lepmik** [comment]
@dragly that fix is in [expipe-plugin-cinpla transfer function](https://github.com/CINPLA/expipe-plugin-cinpla/blob/master/expipe_plugin_cinpla/main.py#L130-L310)

A performance test should absolutely be written, and maybe also a mapping of which processes that eats performance in exdir. 

I agree that archive+transfer cache is maybe not something to be but in exdir as it will probably be a source of much bugs when considering the many ways of communicating with external storage devices.

**Comment by dragly** [comment]
With the improvements we did before the 0.3 release for the paper I think there is little more we can do to improve performance short term. In addition, we now recommend using for instance Git LFS instead of working directly on a server's file system for the typical workflows. I'll close this issue for now.
