### ISSUE TITLE
memmaped array cannot be overwritten by set_data

### ISSUE THREAD

**Issue by lepmik** [CINPLA/exdir#29]
if you load a dataset first and then try to use `set_data` numpy cannot write a new dataset as it is being used by another process

**Comment by lepmik** [comment]
this only happens in some particular cases, more info coming later.

**Comment by dragly** [comment]
Any updates on this @lepmik? Also, any suggestion for which milestone we could use?

**Comment by lepmik** [comment]
The issue arose in phy neo gui, I made a quick workaround by converting to arrays, with the intention to look more closely into it later.  Unfortunately I am unable to reproduce the error now, and I am not sure if that is due to changes in phy. I think we should keep it in mind that these kind of issues can arise, close this issue and focus on #30
