### ISSUE TITLE
Implement close

### ISSUE THREAD

**Issue by simetenn** [CINPLA/exdir#31]
We must decide how file.close() should behave. This is dependent in how numpy mmap works and when/if/ mmap changes/saves files to disk.

**Comment by simetenn** [comment]
When file.close is implemented we should also implement  \_\_enter\_\_ and \_\_exit\_\_ to allow the use of `with`

**Comment by lepmik** [comment]
I suggest we keep it as is; when setting data it's written directly to disk. If so, file.close() does not need to have any function. Or am I missing something here?

**Comment by lepmik** [comment]
Implemented in https://github.com/CINPLA/exdir/pull/85

However, numpy memmaps are not possible to close explicitly; see https://github.com/numpy/numpy/issues/13510
