### ISSUE TITLE
exdir_object.require raw returns different types

### ISSUE THREAD

**Issue by alejoe91** [CINPLA/exdir#34]
if the directory name exists it returns the full path as a string, otherwise it returns a raw object.
It should always return a Raw object

**Comment by alejoe91** [comment]
also maybe here:
https://github.com/CINPLA/exdir/blob/dev/exdir/core/exdir_object.py#L196
`if os.path.exist(directory_name)` should be instead `if os.path.isdir(directory_name):` ?

**Comment by miladh** [comment]
@dragly is this fixed?

**Comment by dragly** [comment]
Yes, it should be. @alejoe91 please reopen the issue if you still have problems.
