### ISSUE TITLE
Plugin dependency handling

### ISSUE THREAD

**Issue by dragly** [CINPLA/exdir#37]
Plugins should have the following three attributes that are resolved at load-time:

* Dependencies: Defines which other plugins must be present together with this plugin.
* ReadAfter: Defines plugins that must be run after this plugin when reading data.
* WriteAfter: Same as above, for writing after other plugins.
* ReadBefore: Same as above, for reading before other plugins.
* WriteBefore: Same as above, for writing before other plugins.

**Comment by simetenn** [comment]
This is solved in pull request #38.
