### ISSUE TITLE
Python2.7.x support

### ISSUE THREAD

**Issue by espenhgn** [CINPLA/exdir#52]
End of life of Python 2.7 is in 2020 (https://www.python.org/dev/peps/pep-0373/#id2) but may still be around after that. Any plans for patching in 2.7 support? I cannot now for example easily replace the h5py dependency in LFPy (h5py 2.8.0 breaks some tests in LFPy and I would like to get rid of it) with exdir, as LFPy should continue to work with Python 2.7 (for now).

**Comment by dragly** [comment]
This was added in 1b60af8bf3ea00b703fb464e515e110f82b3bbb4
