### ISSUE TITLE
Testing: assert f

### ISSUE THREAD

**Issue by lepmik** [CINPLA/exdir#78]
There are some tests that asserts on the variable after it has been created, it fails on my computer but obviously not on Travis. It's probably some package issue on my end, but I find these assertions a bit hard to read - what exactly is tested? I suggest we either edit them into specifics, e.g. the example below would be `assert isinstance(f, exdir.File)` or remove them.

For example here:
https://github.com/CINPLA/exdir/blob/7a1860fd737222747327d66f3b5b414801e4d25f/tests/test_file.py#L92-L95

**Comment by miladh** [comment]
I think explicit tests are better, so +1 for: `assert isinstance(f, exdir.File)`

**Comment by lepmik** [comment]
fixed in #80
